// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCrbR-G_xHhb5Tta25SYqnLkRAj18zv0',
    appId: '1:694093912795:web:a12862da3e255545548afe',
    messagingSenderId: '694093912795',
    projectId: 'horarioscba',
    authDomain: 'horarioscba.firebaseapp.com',
    storageBucket: 'horarioscba.appspot.com',
    measurementId: 'G-KV17ZDS9QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGHjax3RXdzDUHSNYt1y8WcjvoAIwWgA',
    appId: '1:694093912795:android:4e811559cf21da94548afe',
    messagingSenderId: '694093912795',
    projectId: 'horarioscba',
    storageBucket: 'horarioscba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtXnF2SKeoQ6GxG0qeuOeyzW3Yn9HmlmU',
    appId: '1:694093912795:ios:e9876ee02b3afd03548afe',
    messagingSenderId: '694093912795',
    projectId: 'horarioscba',
    storageBucket: 'horarioscba.appspot.com',
    iosBundleId: 'com.example.horariosCba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtXnF2SKeoQ6GxG0qeuOeyzW3Yn9HmlmU',
    appId: '1:694093912795:ios:e9876ee02b3afd03548afe',
    messagingSenderId: '694093912795',
    projectId: 'horarioscba',
    storageBucket: 'horarioscba.appspot.com',
    iosBundleId: 'com.example.horariosCba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcCrbR-G_xHhb5Tta25SYqnLkRAj18zv0',
    appId: '1:694093912795:web:b82d8367fb40fd9c548afe',
    messagingSenderId: '694093912795',
    projectId: 'horarioscba',
    authDomain: 'horarioscba.firebaseapp.com',
    storageBucket: 'horarioscba.appspot.com',
    measurementId: 'G-L7PVBMBGH4',
  );
}
